config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace 'my' do
    root to: 'dashboard#index'
    put :terminate_coin_bank, to: 'dashboard#terminate_coin_bank'

    get 'projects', to: 'dashboard#projects'

    resource :contributing_projects, 'contributing_projects'
    resources :accounts do
      get :upload_csv, on: :member
      post :process_csv, on: :member
    end
  end

  resources :projects do
    resource :account, controller: 'projects/accounts'
  end

  resources :users
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id          :integer          not null, primary key
#  title       :string
#  description :text
#  image_url   :string
#  owner_id    :integer
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  public      :boolean          default("false")
#  uuid        :string
#
# Indexes
#
#  index_projects_on_owner_id  (owner_id)
#

class Project < ApplicationRecord
  belongs_to :owner, class_name: 'User'

  has_one :account, class_name: 'WithdrawalAccount'
  has_many :transactions, through: :account
  has_many :project_users
  has_many :contributing_users, class_name: 'User', through: :project_users, source: :user

  validates_presence_of :title, :description, :image_url, :uuid

  before_validation :generate_uuid

  def self.search(search)
    return all if search.nil?
    where('name ILIKE ?', "%#{search}%")
    where('description ILIKE ?', "%#{search}%")
  end

  def self.public
    where(public: true)
  end

  def total_contributed
    self.transactions.sum(&:price)
  end

  def to_param
    self.uuid
  end

  protected

  def generate_uuid
    self.uuid ||= SecureRandom.uuid
  end
end

app/controllers/projects/accounts_controller.rb
class Projects::AccountsController < ApplicationController
  before_action :set_project
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /projects/accounts/1
  def show
  end

  # GET /projects/accounts/new
  def new
    @account = @project.build_account
  end

  # GET /projects/accounts/1/edit
  def edit
  end

  # POST /projects/accounts
  def create
    @account = @project.build_account(account_params)

    if @account.save
      redirect_to project_account_path(@project, @account), notice: 'Conta salva com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/accounts/1
  def update
    if @account.update(account_params)
      redirect_to project_account_path(@project), notice: 'Conta alterada com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /projects/accounts/1
  def destroy
    @account.destroy
    redirect_to @project, notice: 'Conta excluída com sucesso.'
  end

  private
  def set_project
    @project = current_user.own_projects.find_by(uuid: params[:project_id])
  end

  def set_account
    @account = @project.account
  end

  # Only allow a trusted parameter "white list" through.
  def account_params
    params.require(:withdrawal_account).permit(:service, :email, :account, :agency)
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show]
  before_action :set_project_from_current_user, only: [:edit, :update, :destroy]

  # GET /projects
  def index
    @projects = Project.search(params[:search]).public
  end

  # GET /projects/1
  def show
  end

  # GET /projects/new
  def new
    @project = current_user.own_projects.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  def create
    @project = current_user.own_projects.new(project_params)

    if @project.save
      redirect_to new_project_account_path(@project), notice: 'Causa salva com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/1
  def update
    if @project.update(project_params)
      redirect_to @project, notice: 'Causa alterada com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /projects/1
  def destroy
    @project.destroy
    redirect_to projects_url, notice: 'Causa excluída com sucesso.'
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_project
    @project = Project.find_by(uuid: params[:id])
  end

  def set_project_from_current_user
    @project = current_user.own_projects.find_by(uuid: params[:id])
  end

  # Only allow a trusted parameter "white list" through.
  def project_params
    params.require(:project).permit(:title, :description, :image_url, :public)
  end
end

app/helpers/projects/accounts_helper.rb
module Projects::AccountsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_form.html.haml
= simple_form_for(@project) do |f|
  = f.error_notification

  .form-inputs
    = f.input :title
    = f.input :description
    = f.input :image_url
    = f.input :public, hint: 'Causas públicas irão aparecer na busca e na página de causas'

  %br

  .form-actions
    = f.button :submit

app/views/projects/_list.html.haml
.projects-list-horizontal
  - projects.each do |project|
    - if project.project.public
      = link_to project.project do
        .card.horizontal
          .project-image-container.card-image
            = image_tag project.image_url, class: 'project-image'
          .project-content.card-content
            .card-title
              = project.title
            = project.description

app/views/projects/_search.html.haml
.projects-search
  = form_tag projects_path, method: 'get', class: 'projects-search-form' do
    = text_field_tag :search, params[:search], placeholder: 'Busque por causas', class: 'projects-search-submit'
    = button_tag type: 'submit', class: 'projects-search-submit waves-effect waves-light btn' do
      %i.material-icons
        search

app/views/projects/edit.html.haml
%h1 Editar causa

= render 'form'

app/views/projects/index.html.haml
.projects-header
  %h3 Causas
  = link_to 'Adicionar Causa', new_project_path, { class: 'waves-effect waves-light btn' }

= render 'projects/search'
.projects-list.masonry-layout
  - @projects.each do |project|
    = link_to project do
      .masonry-layout-panel
        .masonry-layout-panel-content
          .card
            .project-image-container.card-image
              = image_tag project.image_url, class: 'project-image'
            .project-content.card-content
              .project-title.card-title
                %span
                  = project.title
                .chip.lime.accent-4
                  = "R$ #{project.total_contributed}"
              .card-description= project.description

app/views/projects/new.html.haml
%h3.title Adicionar Causa

= render 'form'

app/views/projects/show.html.haml
.projects-header
  %h3 Causa
  - if current_user == @project.owner
    %div
      = link_to 'Editar', edit_project_path(@project), class: 'waves-effect waves-light btn'
      = link_to @project, method: :delete,
                data: { confirm: 'Você tem certeza?' }, class: 'waves-effect waves-light btn red' do
        %i.material-icons.left
          archive
        Arquivar

.project-page
  .card
    .project-image-container.card-image
      = image_tag @project.image_url, class: 'project-image'
    .project-content.card-content
      .project-title.card-title
        %span
          = @project.title
        .chip.lime.accent-4
          = "R$ #{@project.total_contributed}"
        - unless @project.public
          .chip
            %i.material-icons lock

      = @project.description

    - if current_user == @project.owner
      .card-action
        - if @project.account
          = link_to 'Ver Conta', project_account_path(@project)
          = link_to 'Editar Conta', edit_project_account_path(@project)
        - else
          = link_to 'Adicionar Conta', new_project_account_path(@project)

- if @project.contributing_users.any?
  %h5.title Usuários que suportam esta causa

  = render partial: 'users/list', locals: { users: @project.contributing_users }