config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace 'my' do
    root to: 'dashboard#index'
    put :terminate_coin_bank, to: 'dashboard#terminate_coin_bank'

    get 'projects', to: 'dashboard#projects'

    resource :contributing_projects, 'contributing_projects'
    resources :accounts do
      get :upload_csv, on: :member
      post :process_csv, on: :member
    end
  end

  resources :projects do
    resource :account, controller: 'projects/accounts'
  end

  resources :users
end

app/controllers/my/accounts_controller.rb
class My::AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :process_csv]

  def index
    @accounts = current_user.accounts.all
  end

  def show
  end

  def new
    @account = current_user.accounts.new
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)

    if @account.save
      redirect_to my_accounts_path, notice: 'Conta salva com sucesso.'
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to my_accounts_path, notice: 'Conta alterada com sucesso.'
    else
      render :edit
    end
  end

  def upload_csv

  end

  def process_csv
    count = Transactions::ImportCsv.new(@account, params['csv']['file'].tempfile.path).process

    redirect_to my_accounts_path, notice: "#{count} registros importados com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.accounts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def account_params
      params.require(:source_account).permit(:service, :email, :password, :account, :agency)
    end
end

app/controllers/my/contributing_projects_controller.rb
class My::ContributingProjectsController < ApplicationController
  def edit
    @contributing_projects = current_user.contributing_projects
    @projects_available = Project.where.not(id: @contributing_projects.map(&:project_id))
    @new_project = ProjectUser.new
  end

  def update
    service = UpdateContributingProjects.new(current_user)
    service.call(params)

    redirect_to({ action: :edit }, notice: 'Contribuições atualizadas com sucesso.')
  end
end

app/controllers/my/dashboard_controller.rb
class My::DashboardController < ApplicationController
  def index
    @contributing_projects = current_user.contributing_projects
    @coin_banks = current_user.coin_banks
  end

  def projects
    @projects = current_user.own_projects
  end

  def terminate_coin_bank
    TerminateCoinBank.new(current_user.coin_banks.active).call

    redirect_to my_root_path,
                notice: 'Cofrinho finalizado com sucesso. Um novo cofrinho foi criado.'
  end
end

app/controllers/projects/accounts_controller.rb
class Projects::AccountsController < ApplicationController
  before_action :set_project
  before_action :set_account, only: [:show, :edit, :update, :destroy]

  # GET /projects/accounts/1
  def show
  end

  # GET /projects/accounts/new
  def new
    @account = @project.build_account
  end

  # GET /projects/accounts/1/edit
  def edit
  end

  # POST /projects/accounts
  def create
    @account = @project.build_account(account_params)

    if @account.save
      redirect_to project_account_path(@project, @account), notice: 'Conta salva com sucesso.'
    else
      render :new
    end
  end

  # PATCH/PUT /projects/accounts/1
  def update
    if @account.update(account_params)
      redirect_to project_account_path(@project), notice: 'Conta alterada com sucesso.'
    else
      render :edit
    end
  end

  # DELETE /projects/accounts/1
  def destroy
    @account.destroy
    redirect_to @project, notice: 'Conta excluída com sucesso.'
  end

  private
  def set_project
    @project = current_user.own_projects.find_by(uuid: params[:project_id])
  end

  def set_account
    @account = @project.account
  end

  # Only allow a trusted parameter "white list" through.
  def account_params
    params.require(:withdrawal_account).permit(:service, :email, :account, :agency)
  end
end

app/helpers/my/accounts_helper.rb
module My::AccountsHelper
end

app/helpers/projects/accounts_helper.rb
module Projects::AccountsHelper
end

app/views/my/accounts/_form.html.haml
- path = @account.new_record? ? my_accounts_path : my_account_path(@account)

= simple_form_for(@account, url: path) do |f|
  = f.error_notification

  .form-inputs
    = f.select :service, ['Banco do Brasil', 'PayPal', 'NuBank']
    = f.input :agency
    = f.input :account
    = f.input :email
    = f.input :password

  .form-actions
    = f.button :submit

app/views/my/accounts/edit.html.haml
.back-button-box
  = link_to 'Voltar', my_accounts_path, { class: 'waves-effect waves-light btn' }

%h3.title Editar Conta

= render 'form'

app/views/my/accounts/index.html.haml
.projects-header
  %h3 Minhas Contas
  = link_to 'Adicionar Conta', new_my_account_path, { class: 'waves-effect waves-light btn' }

- if @accounts.empty?
  .center-align
    %h5 Você ainda não possui nenhuma conta cadastrada.
- else
  %table
    %thead
      %tr
        %th Serviço
        %th Total Transações
        %th Total Cofrinho
        %th
        %th

    %tbody
      - @accounts.each do |account|
        %tr
          %td
            .account-box
              %img.circle.account-logo{ src: account_logo(account.service) }
              %strong= account.service
          %td= "R$ #{account.transactions.sum(&:price)}"
          %td
            %strong.chip.lime.accent-4= "R$ #{account.savings.sum(&:price)}"
          %td= link_to 'Mostrar', my_account_path(account), { class: 'waves-effect waves-light btn' }
          %td= link_to 'Editar', edit_my_account_path(account), { class: 'waves-effect waves-light btn' }

app/views/my/accounts/new.html.haml
.back-button-box
  = link_to 'Voltar', my_accounts_path, { class: 'waves-effect waves-light btn' }

%h3.title Nova Conta

= render 'form'

app/views/my/accounts/show.html.haml
.projects-header
  %h3= @account.service
  = link_to 'Editar', edit_my_account_path(@account), { class: 'waves-effect waves-light btn' }

- if @account.transactions.empty?
  %h5 Esta conta ainda não possui nenhuma transação.
- else

  = line_chart @account.transactions.map { |t| [t.transaction_date, t.price.to_f] }

  %table.striped
    %thead
      %tr
        %th Código
        %th Criado em
        %th.col.s8 Descrição
        %th Valor
        %th Cofrinho

    %tbody
      - @account.transactions.each do |transaction|
        %tr
          %td= transaction.external_id
          %td= transaction.transaction_date
          %td
            %strong= transaction.description
          %td
            %strong= "R$ #{transaction.price}"
          %td
            %strong.chip.lime.accent-4= "R$ #{transaction.saving.price}"

      %tr
        %td
        %td
        %td
          %strong Total
        %td
          %strong= "R$ #{@account.transactions.sum(&:price)}"
        %td
          %strong.chip.lime.accent-4= "R$ #{@account.savings.sum(&:price)}"
%br

.row
  .col.sm2
  = link_to 'Enviar CSV', upload_csv_my_account_path(@account), { class: 'waves-effect waves-light btn' }

app/views/my/accounts/upload_csv.html.haml
%h3.title Enviar CSV com transações

= simple_form_for :csv, url: process_csv_my_account_path do |f|
  = f.input :file, as: :file, label: 'Arquivo CSV'

  = f.button :submit