config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace 'my' do
    root to: 'dashboard#index'
    put :terminate_coin_bank, to: 'dashboard#terminate_coin_bank'

    get 'projects', to: 'dashboard#projects'

    resource :contributing_projects, 'contributing_projects'
    resources :accounts do
      get :upload_csv, on: :member
      post :process_csv, on: :member
    end
  end

  resources :projects do
    resource :account, controller: 'projects/accounts'
  end

  resources :users
end

app/controllers/my/accounts_controller.rb
class My::AccountsController < ApplicationController
  before_action :set_account, only: [:show, :edit, :update, :destroy, :process_csv]

  def index
    @accounts = current_user.accounts.all
  end

  def show
  end

  def new
    @account = current_user.accounts.new
  end

  def edit
  end

  def create
    @account = current_user.accounts.new(account_params)

    if @account.save
      redirect_to my_accounts_path, notice: 'Conta salva com sucesso.'
    else
      render :new
    end
  end

  def update
    if @account.update(account_params)
      redirect_to my_accounts_path, notice: 'Conta alterada com sucesso.'
    else
      render :edit
    end
  end

  def upload_csv

  end

  def process_csv
    count = Transactions::ImportCsv.new(@account, params['csv']['file'].tempfile.path).process

    redirect_to my_accounts_path, notice: "#{count} registros importados com sucesso."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_account
      @account = current_user.accounts.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def account_params
      params.require(:source_account).permit(:service, :email, :password, :account, :agency)
    end
end

app/controllers/my/contributing_projects_controller.rb
class My::ContributingProjectsController < ApplicationController
  def edit
    @contributing_projects = current_user.contributing_projects
    @projects_available = Project.where.not(id: @contributing_projects.map(&:project_id))
    @new_project = ProjectUser.new
  end

  def update
    service = UpdateContributingProjects.new(current_user)
    service.call(params)

    redirect_to({ action: :edit }, notice: 'Contribuições atualizadas com sucesso.')
  end
end

app/controllers/my/dashboard_controller.rb
class My::DashboardController < ApplicationController
  def index
    @contributing_projects = current_user.contributing_projects
    @coin_banks = current_user.coin_banks
  end

  def projects
    @projects = current_user.own_projects
  end

  def terminate_coin_bank
    TerminateCoinBank.new(current_user.coin_banks.active).call

    redirect_to my_root_path,
                notice: 'Cofrinho finalizado com sucesso. Um novo cofrinho foi criado.'
  end
end

app/helpers/my/accounts_helper.rb
module My::AccountsHelper
end

app/views/my/dashboard/_my_coin_banks.html.haml
.coin-banks-widget
  %ul.collection.with-header
    %li.collection-header
      %strong
        %i.material-icons attach_money

    %li.collection-item
      %strong Cofrinho atual:

    %li.collection-item.center-align
      .light-green-text.accent-4
        %h4= coin_bank_savings_total(@coin_banks.active)

      - if @coin_banks.active.savings.any?
        = link_to 'Fechar Cofrinho', my_terminate_coin_bank_path, method: 'put', class: 'btn'

    - if @coin_banks.inactives.any?
      %li.collection-item
        %strong Cofrinhos anteriores:
        - @coin_banks.inactives.each do |coin_bank|

          %li.collection-item.center-align
            = "#{coin_bank_savings_total(coin_bank)}"
            \/
            %strong= "#{coin_bank.terminated_at.strftime('%b %y').upcase}"

app/views/my/dashboard/_my_contributions.html.haml
.contributions-widget
  - if @contributing_projects.any?
    - @contributing_projects.each do |project|
      = link_to project.project do
        .card.horizontal
          .card-image.project-image-container
            = image_tag project.image_url, class: 'project-image'
          .card-content
            %strong.project-title
              = project.title
            .project-percentage
              %strong
                = "#{project.percentage}%"
                = "ou R$ #{project.min}" if project.min > 0

    = link_to 'Atualizar', edit_my_contributing_projects_path, class: 'waves-effect waves-light btn'

  - else
    .center-align
      %h5 Você ainda não selecionou nenhuma causa para contribuir! Escolha uma das causas públicas ou crie a sua própria causa.
      = link_to 'Selecionar Causas', edit_my_contributing_projects_path, class: 'waves-effect waves-light btn'

app/views/my/dashboard/index.html.haml
.dashboard
  .flex-horizontal
    = render 'my_contributions'
    = render 'my_coin_banks'

  .coin-banks-historical.card
    %h5.title Histórico dos cofrinhos
    = line_chart current_user.coin_banks.inactives.map { |cb| [cb.terminated_at, cb.savings.map(&:price).sum.to_f] }

app/views/my/dashboard/projects.html.haml
.projects-header
  %h3 Minhas Causas
  = link_to 'Adicionar Causa', new_project_path, { class: 'waves-effect waves-light btn' }

- if @projects.empty?
  %h5.center-align Você ainda não possui nenhuma causa cadastrada.
- else
  .projects-list.masonry-layout
    - @projects.each do |project|
      = link_to project do
        .masonry-layout-panel
          .masonry-layout-panel-content
            .card
              .project-image-container.card-image
                = image_tag project.image_url, class: 'project-image'
              .project-content.card-content
                .project-title.card-title
                  %span
                    = project.title
                  .chip.lime.accent-4
                    = "R$ #{project.total_contributed}"
                  - unless project.public
                    .chip
                      %i.material-icons lock
                .card-description= project.description