config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
             path: '',
             path_names: { sign_in: 'login', sign_out: 'logout' },
             controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

  namespace 'my' do
    root to: 'dashboard#index'
    put :terminate_coin_bank, to: 'dashboard#terminate_coin_bank'

    get 'projects', to: 'dashboard#projects'

    resource :contributing_projects, 'contributing_projects'
    resources :accounts do
      get :upload_csv, on: :member
      post :process_csv, on: :member
    end
  end

  resources :projects do
    resource :account, controller: 'projects/accounts'
  end

  resources :users
end

app/views/layouts/_app_header.html.haml
%nav.app-header
  .nav-wrapper
    = link_to my_root_path, class: 'brand-logo' do
      = image_tag 'piggy-bank.png', class: 'logo'
      %span.brand Troquinho
    - if current_user
      %ul.right.hide-on-med-and-down
        %li
          = link_to 'Sair', destroy_user_session_path, method: :delete

app/views/layouts/_side_nav.html.haml
%ul#side-nav.side-nav.fixed
  %li
    .userView
      %img.circle{ src: current_user.image_url }
      %span.name
        = current_user.name
      %span.email
        = current_user.email

  = nav_link my_root_path do
    %i.material-icons attach_money
    Meu Cofrinho

  = nav_link my_accounts_path do
    %i.material-icons account_balance_wallet
    Minhas Contas

  = nav_link projects_path do
    %i.material-icons apps
    Causas

  %li
    %ul
      = nav_link my_projects_path do
        %i.material-icons person_pin
        Minhas Causas

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Troquinho
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    - if current_user
      = render 'layouts/side_nav'
    #main-page
      = render 'layouts/app_header'
      - if notice
        .notice-message.light-green.darken-3
          .white-text
            = notice

      #main-content
        = yield